### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 20000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 1000
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "53408a639db9489a85c373ddbb92bd64",
  "accountNumber": "1000000002",
  "amount" : 30000
}

### query transaction
GET http://localhost:8080/transaction/53408a639db9489a85c373ddbb92bd64